export const SCOPES: Record<string, string[]> = {
  user: [
    "patient:read",
    "patient:write",
    "patient:update",
    "monitoring:read",
    "monitoring:write",
    "monitoring:update",
    "appointment:read",
    "appointment:write",
    "appointment:update",
    "medication:read",
    "medication:write",
    "medication:update",
  ],
  doctor: [
    "patient:read",
    "doctor:read",
    "doctor:update",
    "monitoring:read",
    "medication:read",
    "medication:update",
    "appointment:read",
    "appointment:write",
    "appointment:update",
  ],
  admin: [
    "users:read",
    "users:write",
    "users:update",
    "users:delete",
    "appointment:read",
    "appointment:write",
    "appointment:update",
    "appointment:delete",
    "monitoring:read",
    "monitoring:delete",
    "medication:read",
    "medication:delete",
  ],
}
