patients_data = [
  {
    "email": "walterwhite@gguide.com",
    "name": "Walter White",
    "gender": "male",
    "address": "Dhanmondi, Dhaka-1205",
    "profession": "Chemistry Teacher",
    "date_of_birth": "09/07/1959",
    "contact_number": "01714787281",
    "emergency_number": "01876263512",
    "created_by": "seeding"
  },
  {
    "email": "skylerwhite@gguide.com",
    "name": "Skyler White",
    "gender": "female",
    "address": "Gulshan, Dhaka-1212",
    "profession": "Accountant",
    "date_of_birth": "08/11/1967",
    "contact_number": "01987646745",
    "emergency_number": "01822334455",
    "created_by": "seeding"
  },
  {
    "email": "hankschrader@gguide.com",
    "name": "Hank Schrader",
    "gender": "male",
    "address": "Mirpur, Dhaka-1216",
    "profession": "DEA Agent",
    "date_of_birth": "04/18/1966",
    "contact_number": "01378782762",
    "emergency_number": "01912763662",
    "created_by": "seeding"
  },
  {
    "email": "marieschrader@gguide.com",
    "name": "Marie Schrader",
    "gender": "female",
    "address": "Banani, Dhaka-1213",
    "profession": "Radiologic Technologist",
    "date_of_birth": "10/17/1968",
    "contact_number": "01714565454",
    "emergency_number": "01684646781",
    "created_by": "seeding"
  },
  {
    "email": "saulgoodman@gguide.com",
    "name": "Saul Goodman",
    "gender": "male",
    "address": "Mohakhali, Dhaka-1212",
    "profession": "Lawyer",
    "date_of_birth": "11/12/1960",
    "contact_number": "01616872101",
    "emergency_number": "01746867091",
    "created_by": "seeding"
  },
  {
    "email": "gustavofring@gguide.com",
    "name": "Gustavo Fring",
    "gender": "male",
    "address": "Uttara, Dhaka-1230",
    "profession": "Businessman",
    "date_of_birth": "06/23/1963",
    "contact_number": "01993131521",
    "emergency_number": "01934289767",
    "created_by": "seeding"
  },
  {
    "email": "mikeehrmantraut@gguide.com",
    "name": "Mike Ehrmantraut",
    "gender": "male",
    "address": "Bashundhara, Dhaka-1229",
    "profession": "Private Investigator",
    "date_of_birth": "02/06/1944",
    "contact_number": "01714687691",
    "emergency_number": "01888467181",
    "created_by": "seeding"
  },
  {
    "email": "lydiasharp@gguide.com",
    "name": "Lydia Sharp",
    "gender": "female",
    "address": "Banasree, Dhaka-1219",
    "profession": "Executive",
    "date_of_birth": "03/29/1978",
    "contact_number": "01914578920",
    "emergency_number": "01912181931",
    "created_by": "seeding"
  },
  {
    "email": "toddalquist@gguide.com",
    "name": "Todd Alquist",
    "gender": "male",
    "address": "Baridhara, Dhaka-1212",
    "profession": "Lab Assistant",
    "date_of_birth": "11/11/1987",
    "contact_number": "01614698181",
    "emergency_number": "01883132761",
    "created_by": "seeding"
  },
  {
    "email": "janesmith@gguide.com",
    "name": "Jane Smith",
    "gender": "female",
    "address": "Shantinagar, Dhaka-1217",
    "profession": "Artist",
    "date_of_birth": "08/03/1990",
    "contact_number": "01614564721",
    "emergency_number": "01912444424",
    "created_by": "seeding"
  }
]

hospitals_data = [
  {
    "name": "Square Hospital Dhaka",
    "address": "18/F, West Panthapath",
    "city": "Panthapath",
    "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1725012552/glucoguide/hospitals/square-hospital.jpg",
    "description": "Square Hospital is a leading private hospital in Dhaka known for its specialized care and state-of-the-art facilities.",
    "emails": ["contact@squarehospital.com", "support@squarehospital.com"],
    "contact_numbers": ["+88028214111", "+88029676767"],
    "geometry": {
      "coordinates": [90.381673, 23.7530335],
      "type": "Point",
    },
  },
  {
    "name": "Evercare Hospital Dhaka",
    "address": "Plot 81, Block-E, Bashundhara, Dhaka-1229",
    "city": "Bashundhara",
    "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1725012552/glucoguide/hospitals/evercare-hospital.jpg",
    "description": "Apollo Hospitals Dhaka is a renowned multi-specialty hospital known for its advanced medical treatments and patient care.",
    "emails": ["appointment@evercaredhaka.com", "info@evercaredhaka.com"],
    "contact_numbers": ["+880248008000", "+8801787685678"],
    "geometry": {
      "coordinates": [90.43126960143593, 23.809932148541805],
      "type": "Point",
    },
  },
  {
    "name": "Anwar Khan Modern Hospital Dhaka",
    "address": "House-17, Road-8,Dhanmondi, Dhaka-1207",
    "city": "Dhanmondi",
    "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1725012552/glucoguide/hospitals/anwar-hospital.jpg",
    "description": "Anwar Khan Modern Hospital is a dedicated facility for cardiac care, offering advanced treatments and surgery.",
    "emails": ["info@anwarkhanhospital.org", "appointment@anwarkhanhospital.org"],
    "contact_numbers": ["+88029166663", "+88029150394"],
    "geometry": {
      "coordinates": [90.382087, 23.74531],
      "type": "Point",
    },
  },
  {
    "name": "United Hospital Limited",
    "address": "Plot-15, Road-71, Gulshan-2, Dhaka-1212",
    "city": "Gulshan",
    "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1725012552/glucoguide/hospitals/united-hospital.jpg",
    "description": "United Hospital provides comprehensive healthcare services with a focus on cardiology, oncology, and emergency care.",
    "emails": ["info@uhlbd.com"], 
    "contact_numbers": ["+880258150000"],
    "geometry": {
      "coordinates": [90.415832, 23.804858],
      "type": "Point",
    },
  },
  {
    "name": "Ibne Sina Hospital Dhaka (Dhanmondi)",
    "address": "House No. 70, Road-15/A, Dhanmondi, Dhaka-1209",
    "city": "Dhanmondi",
    "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1725012552/glucoguide/hospitals/ibn-sina-hospital.jpg",
    "description": "Ibne Sina Hospital provides a range of healthcare services with a focus on patient satisfaction and quality care.",
    "emails": ["info@ibnsinahospital.com", "support@ibnsinahospital.com"],
    "contact_numbers": ["+880258048321", "+8801675119999"],
    "geometry": {
      "coordinates": [90.37276, 23.745001],
      "type": "Point",
    },
  },
  {
    "name": "Labaid Specialized Hospital (Dhanmondi)",
    "address": "House-1, Road-4, Dhanmondi Dhaka-1205",
    "city": "Dhanmondi",
    "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1725012552/glucoguide/hospitals/labaid-hospital.jpg",
    "description": "Labaid Hospital Dhaka is a leading healthcare provider in the country, known for its excellence in cardiology and surgery.",
    "emails": ["info@labaidhospital.com", "support@labaidhospital.com"],
    "contact_numbers": ["+88029677885", "+8801755566222"],
    "geometry": {
      "coordinates": [90.383135, 23.741687499999998],
      "type": "Point",
    },
  },
  {
    "name": "Labaid Specialized Hospital (Gulshan)",
    "address": "House-13/A, Road-35, Gulshan-2, Dhaka-1212",
    "city": "Gulshan",
    "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1725012552/glucoguide/hospitals/labaid-hospital.jpg",
    "description": "Labaid Hospital Dhaka is a leading healthcare provider in the country, known for its excellence in cardiology and surgery.",
    "emails": ["info@labaidhospital.com", "support@labaidhospital.com"],
    "contact_numbers": ["+88029666825", "+8801755611222"],
    "geometry": {
      "coordinates": [90.412907, 23.794089],
      "type": "Point",
    },
  },
  {
    "name": "Popular Diagnostic Center (Dhanmondi)",
    "address": "House-16, Road-2, Dhanmondi, Dhaka-1205",
    "city": "Dhanmondi",
    "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1725012552/glucoguide/hospitals/popular-hospital.jpg",
    "description": "Popular Diagnostic Centre is a prominent medical diagnostic and healthcare service provider in Dhaka.",
    "emails": ["contact@populardiagnostic.com"],
    "contact_numbers": ["+880255071801"],
    "geometry": {
      "coordinates": [90.381667, 23.739226],
      "type": "Point",
    },
  },
  {
    "name": "Popular Diagnostic Center (Uttara)",
    "address": "House-25, Road-07, Sector-04, Jashim Uddin Moar, Uttara, Dhaka-1230",
    "city": "Uttara",
    "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1725012552/glucoguide/hospitals/popular-hospital.jpg",
    "description": "Popular Diagnostic Centre is a prominent medical diagnostic and healthcare service provider in Dhaka.",
    "emails": ["contact@populardiagnostic.com"],
    "contact_numbers": ["+880255071801"],
    "geometry": {
      "coordinates": [90.400331, 23.860908],
      "type": "Point",
    },
  },
  {
    "name": "Ibne Sina Hospital Dhaka (Mirpur)",
    "address": "Hazi Road, Shiyalbari Moor, 2 Avenue-03, Mirpur-02, Dhaka-1216",
    "city": "Mirpur",
    "img_src":
      "https://res.cloudinary.com/dwhlynqj3/image/upload/v1725012552/glucoguide/hospitals/ibn-sina-hospital.jpg",
    "description":
      "Ibne Sina Hospital provides a range of healthcare services with a focus on patient satisfaction and quality care.",
    "emails": ["info@ibnsinahospital.com", "support@ibnsinahospital.com"],
    "contact_numbers": ["+880256048222", "+8801675227777"],
    "geometry": {
      "coordinates": [90.3622604597759, 23.77844844009768],
      "type": "Point",
    },
  },
  {
    "name": "Dhaka Medical College",
    "address": "Secretariat Road, Shahbag, Dhaka-1000",
    "city": "Ramna",
    "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1725012552/glucoguide/hospitals/dhaka-medical.jpg",
    "description": "Dhaka Medical College Hospital is one of the largest public hospitals in Bangladesh, offering a wide range of healthcare services.",
    "emails": ["info@dmch.gov.bd"],
    "contact_numbers": ["+88029551156"],
    "geometry": {
      "coordinates": [90.3975835, 23.7257475],
      "type": "Point",
    },
  },
  {
    "name": "Birdem General Hospital",
    "address": "122 Kazi Nazrul Islam Avenue, Shahbag, Dhaka-1000",
    "city": "Ramna",
    "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1725012552/glucoguide/hospitals/birdem-hospital.jpg",
    "description": "BIRDEM General Hospital specializes in diabetes care and is one of the most respected institutions in Dhaka.",
    "emails": ["info@birdemhospital.org"],
    "contact_numbers": ["+88029557791"],
    "geometry": {
      "coordinates": [90.396719, 23.73925],
      "type": "Point",
    },
  },
  {
    "name": "Holy Family Red Crescent Medical College",
    "address": "1 Eskatan Garden Road, Ramna, Dhaka-1000",
    "city": "Ramna",
    "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1725012552/glucoguide/hospitals/red-crescent-hospital.jpg",
    "description": "Holy Family Red Crescent Medical College Hospital offers comprehensive healthcare services with a focus on medical education.",
    "emails": ["info@hfrcmch.com", "admission@hfrcmch.com"],
    "contact_numbers": ["+88029348602", "+8801552015666"],
    "geometry": {
      "coordinates": [90.401716, 23.746023],
      "type": "Point",
    },
  },
  {
    "name": "Mugda Medical College & Hospital",
    "address": "Hazi Kadam Ali Road, Mugda, Dhaka-1214",
    "city": "Mugda",
    "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1725012552/glucoguide/hospitals/mugda-hospital.jpg",
    "description": "Mugda Medical College & Hospital is a well-known private hospital in Dhaka offering a wide range of medical services.",
    "emails": ["contact@mdchdhaka.com"],
    "contact_numbers": ["+88029676035"],
    "geometry": {
      "coordinates": [90.430053, 23.732472],
      "type": "Point",
    },
  },
  {
    "name": "Badda General Hospital",
    "address": "107/2, Uttar Badda, Progoti Sarani, Dhaka-1212",
    "city": "Gulshan",
    "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1725012552/glucoguide/hospitals/badda-hospital.jpg",
    "description": "Badda General Hospital is a private hospital providing healthcare services and medical education.",
    "emails": ["info@bdgh.org", "admin@bdgh.org"],
    "contact_numbers": ["+88029131515", "+88029145729"],
    "geometry": {
      "coordinates": [90.425663, 23.784485],
      "type": "Point",
    },
  },
  {
    "name": "Impulse Hospital",
    "address": "304/E Shaheed Tazuddin Avenue,Tejgaon, Dhaka-1215",
    "city": "Tejgaon",
    "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1725012552/glucoguide/hospitals/impulse-hospital.jpg",
    "description": "Impulse Hospital is a specialized hospital focusing on diabetes care and research.",
    "emails": ["info@impulse.org"],
    "contact_numbers": ["+880258155672"],
    "geometry": {
      "coordinates": [90.398749, 23.767836],
      "type": "Point",
    },
  },
  {
    "name": "Addin Medical College Hospital",
    "address": "2 Bara Maghbazar, Outer Circular Road, Dhaka-1217",
    "city": "Ramna",
    "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1725012552/glucoguide/hospitals/addin-medical.jpg",
    "description": "Ad-Din Hospital offers affordable healthcare services and is known for its maternal and child healthcare programs.",
    "emails": ["info@addinhospital.com"],
    "contact_numbers": ["+88028311515"],
    "geometry": {
      "coordinates": [90.405218, 23.748836],
      "type": "Point",
    },
  },
  {
    "name": "Farazy Hospital",
    "address": "House-15, Block-E, Rampura, Dhaka-1219",
    "city": "Rampura",
    "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1725012552/glucoguide/hospitals/farazy-hospital.jpg",
    "description": "Farazy Hospital provides affordable healthcare services to the underserved population of Dhaka.",
    "emails": ["info@farazy.org"],
    "contact_numbers": ["+880258145923"],
    "geometry": {
      "coordinates": [90.436169, 23.762542],
      "type": "Point",
    },
  },
  {
    "name": "Famous Specialized Hospital",
    "address": "House-05, Block-H, Block-E, Rampura, Dhaka-1219",
    "city": "Ramna",
    "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1725012552/glucoguide/hospitals/famous-hospital.jpg",
    "description": "Famous Specialized Hospital is a leading diabetes treatment facility in Dhaka with state-of-the-art technology.",
    "emails": ["info@famous.org", "diabetes@famous.org"],
    "contact_numbers": ["+880258167500", "+880258167501"],
    "geometry": {
      "coordinates": [90.44344942826072, 23.762023795255956],
      "type": "Point",
    },
  },
  {
    "name": "Central Basabo General Hospital",
    "address": "127, Central Basabo, Central Bashabo, Sobujbag, Dhaka-1214",
    "city": "Basabo",
    "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1725012552/glucoguide/hospitals/basabo-hospital.jpg",
    "description": "Central Basabo General Hospital is one of the oldest hospitals in Dhaka, offering a variety of healthcare services.",
    "emails": ["info@cbgh.org", "contact@info@cbgh.org"],
    "contact_numbers": ["+88029679295", "+88029670266"],
    "geometry": {
      "coordinates": [90.43456630089332, 23.740817551235864],
      "type": "Point",
    },
  },
]

doctors_data = [
   {
    "email": "habib.sqaure@gguide.com",
    "role": "doctor",
    "name": "Ahsan Habib",
    "gender": "male",
    "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1723475421/glucoguide/doctors/doctor_male_1.jpg",
    "address": "Dhanmondi, Dhaka-1205",
    "created_by": "seeding",
    "description": "Specialist in Diabetes and Endocrinology with 15 years of experience.",
    "hospital_name": "Square Hospital Dhaka",
    "available_times": "Mon, Wed, Fri: 10 AM - 8 PM",
    "experience": 5,
    "emails": ["contact@squarehospital.com", "support@squarehospital.com", "habib.sqaure@gguide.com"],
    "contact_numbers": ["+88028214111", "+88029676767", "01376263512"],
  },
  {
    "email": "nusrat.evercare@gguide.com",
    "role": "doctor",
    "name": "Nusrat Jahan",
    "gender": "female",
    "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1723475421/glucoguide/doctors/doctor_female_1.jpg",
    "address": "Plot 81, Block-E, Bashundhara, Dhaka-1229",
    "created_by": "seeding",
    "description": "Renowned Diabetologist, focusing on Type 2 Diabetes management.",
    "hospital_name": "Evercare Hospital Dhaka",
    "available_times": "Tue, Thu, Sat: 9 AM - 9 PM",
    "experience": 6,
    "emails": ["appointment@evercaredhaka.com", "info@evercaredhaka.com", "nustrat.evercare@gguide.com"],
    "contact_numbers": ["+880248008000", "+8801787685678", "01982345741"],
  },
  {
    "email": "moinul.united@gguide.com",
    "role": "doctor",
    "name": "Moinul Islam",
    "gender": "male",
    "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1723475421/glucoguide/doctors/doctor_male_2.jpg",
    "address": "Plot-15, Road-71, Gulshan-2, Dhaka-1212",
    "created_by": "seeding",
    "description": "Endocrinologist with a special interest in pediatric diabetes.",
    "hospital_name": "United Hospital Limited",
    "available_times": "Mon, Thu: 2 PM - 6 PM",
    "experience": 10,
    "emails": ["info@uhlbd.com", "moinul.united@gguide.com"], 
    "contact_numbers": ["+880258150000", "01833332132"],
  },
  {
    "email": "tahmina.ibne@gguide.com",
    "role": "doctor",
    "name": "Tahmina Akter",
    "gender": "female",
    "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1723475421/glucoguide/doctors/doctor_female_2.jpg",
    "address": "House No. 70, Road-15/A, Dhanmondi, Dhaka-1209",
    "created_by": "seeding",
    "description": "Expert in gestational diabetes and diabetic foot care.",
    "hospital_name": "Ibne Sina Hospital Dhaka (Dhanmondi)",
    "available_times": "Sat, Sun: 11 AM - 3 PM",
    "experience": 8,
    "emails": ["info@ibnsinahospital.com", "support@ibnsinahospital.com", "tahmina.ibne@gguide.com"],
    "contact_numbers": ["+880258048321", "+8801675119999", "01921120120"],
  },
  {
    "email": "rafiq.labaid@gguide.com",
    "role": "doctor",
    "name": "Rafiq Azad",
    "gender": "male",
    "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1723475421/glucoguide/doctors/doctor_male_3.jpg",
    "address": "House-1, Road-4, Dhanmondi Dhaka-1205",
    "created_by": "seeding",
    "description": "Diabetologist with 20 years of experience in treating Type 1 and Type 2 Diabetes.",
    "hospital_name": "Labaid Specialized Hospital (Dhanmondi)",
    "available_times": "Mon, Wed, Fri: 4 PM - 8 PM",
    "experience": 12,
    "emails": ["info@labaidhospital.com", "support@labaidhospital.com", "rafiq.labaid@gguide.com"],
    "contact_numbers": ["+88029677885", "+8801755566222", "8801932121912"],
  },
  {
    "email": "sumaiya.popular@gguide.com",
    "role": "doctor",
    "name": "Sumaiya Alam",
    "gender": "female",
    "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1723475421/glucoguide/doctors/doctor_female_3.jpg",
    "address": "House-16, Road-2, Dhanmondi, Dhaka-1205",
    "created_by": "seeding",
    "description": "Specializes in diabetes-related complications and prevention.",
    "hospital_name": "Popular Diagnostic Center (Dhanmondi)",
    "available_times": "Tue, Thu, Sat: 10 AM - 2 PM",
    "experience": 7,
    "emails": ["contact@populardiagnostic.com", "sumaiya.popular@gguide.com"],
    "contact_numbers": ["+880255071801", "01782462710"],
  },
  {
    "email": "abul.popular@gguide.com",
    "hospital_name": "Dhaka Medical College",
    "role": "doctor",
    "name": "Abul Hossain",
    "gender": "male",
    "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1723475421/glucoguide/doctors/doctor_male_4.jpg",
    "address": "Secretariat Road, Shahbag, Dhaka-1000",
    "created_by": "seeding",
    "description": "Endocrinologist with a focus on insulin therapy and diabetes education.",
    "available_times": "Mon, Wed: 9 AM - 1 PM",
    "experience": 8,
    "emails": ["info@dmch.gov.bd", "abul.popular@gguide.com"],
    "contact_numbers": ["+88029551156", "01618977886"],
  },
  {
    "email": "farhana.birdem@gguide.com",
    "hospital_name": "Birdem General Hospital",
    "role": "doctor",
    "name": "Farhana Khan",
    "gender": "female",
    "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1723475421/glucoguide/doctors/doctor_female_4.jpg",
    "address": "122 Kazi Nazrul Islam Avenue, Shahbag, Dhaka-1000",
    "created_by": "seeding",
    "description": "Expert in managing complex cases of diabetes with co-existing conditions.",
    "available_times": "Sun, Tue, Thu: 2 PM - 6 PM",
    "experience": 4,
    "emails": ["info@birdemhospital.org", "farhana.birdem@gguide.com"],
    "contact_numbers": ["+88029557791", "01913488992"],
  },
  {
    "email": "zahir.holy@gguide.com",
    "hospital_name": "Holy Family Red Crescent Medical College",
    "role": "doctor",
    "name": "Zahir Uddin",
    "gender": "male",
    "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1723475421/glucoguide/doctors/doctor_male_5.jpg",
    "address": "1 Eskatan Garden Road, Ramna, Dhaka-1000",
    "created_by": "seeding",
    "description": "Diabetes specialist with a focus on diet and lifestyle management.",
    "available_times": "Mon, Fri: 3 PM - 7 PM",
    "experience": 5,
    "emails": ["info@hfrcmch.com", "admission@hfrcmch.com", "zahir.holy@gguide.com"],
    "contact_numbers": ["+88029348602", "+8801552015666", "01761466672"],
  },
  {
    "email": "mahmuda.holy@gguide.com",
    "hospital_name": "Holy Family Red Crescent Medical College",
    "role": "doctor",
    "name": "Mahmuda Begum",
    "gender": "female",
    "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1723475421/glucoguide/doctors/doctor_female_5.jpg",
    "address": "1 Eskatan Garden Road, Ramna, Dhaka-1000",
    "created_by": "seeding",
    "description": "Senior Diabetologist with expertise in long-term diabetes care.",
    "available_times": "Tue, Thu: 10 AM - 1 PM",
    "experience": 10,
    "emails": ["info@hfrcmch.com", "admission@hfrcmch.com", "mahmuda.holy@gguide.com"],
    "contact_numbers": ["+88029348602", "+8801552015666", "01922266688"],
  },
  {
    "email": "mahbubur.labid@gguide.com",
    "hospital_name": "Labaid Specialized Hospital (Gulshan)",
    "role": "doctor",
    "name": "Mahbubur Rahman",
    "gender": "female",
    "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1723475421/glucoguide/doctors/doctor_male_6.jpg",
    "address": "House-13/A, Road-35, Gulshan-2, Dhaka-1212",
    "created_by": "seeding",
    "description": "Specialist in Diabetes Mellitus and Metabolic Disorders.",
    "available_times": "Mon, Wed, Sat: 5 PM - 9 PM",
    "experience": 6,
    "emails": ["info@labaidhospital.com", "support@labaidhospital.com", "mahbubur.labid@gguide.com"],
    "contact_numbers": ["+88029666825", "+8801755611222", "01884424242"],
  },
  {
    "email": "shahnaz.anwar@gguide.com",
    "hospital_name": "Anwar Khan Modern Hospital Dhaka",
    "role": "doctor",
    "name": "Shahnaz Huda",
    "gender": "female",
    "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1723475421/glucoguide/doctors/doctor_female_6.jpg",
    "address": "House-17, Road-8, Dhanmondi, Dhaka-1207",
    "created_by": "seeding",
    "description": "Diabetes expert with a focus on patient education and self-management.",
    "available_times": "Tue, Thu, Sun: 3 PM - 7 PM",
    "experience": 9,
    "emails": ["info@anwarkhanhospital.org", "appointment@anwarkhanhospital.org"],
    "contact_numbers": ["+88029166663", "+88029150394", "01718999202"],
  },
  {
    "email": "rezaul.labaid@gguide.com",
    "hospital_name": "Labaid Specialized Hospital",
    "role": "doctor",
    "name": "Rezaul Karim",
    "gender": "male",
    "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1723475421/glucoguide/doctors/doctor_male_7.jpg",
    "address": "House-13/A, Road-35, Gulshan-2, Dhaka-1212",
    "created_by": "seeding",
    "description": "Experienced Diabetologist specializing in insulin pump therapy.",
    "available_times": "Mon, Fri: 11 AM - 3 PM",
    "experience": 14,
    "emails": ["info@labaidhospital.com", "support@labaidhospital.com", "rezaul.labaid@gguide.com"],
    "contact_numbers": ["+88029666825", "+8801755611222", "01912182280"],
  },
  {
    "email": "samira.popular@gguide.com",
    "hospital_name": "Popular Diagnostic Center (Uttara)",
    "role": "doctor",
    "name": "Samira Haque",
    "gender": "female",
    "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1723475421/glucoguide/doctors/doctor_female_7.jpg",
    "address": "House-25, Road-07, Sector-04, Jashim Uddin Moar, Uttara, Dhaka-1230",
    "created_by": "seeding",
    "description": "Specializes in the prevention and management of diabetes complications.",
    "available_times": "Mon, Wed: 2 PM - 6 PM",
    "experience": 6,
    "emails": ["contact@populardiagnostic.com", "samira.popular@gguide.com"],
    "contact_numbers": ["+880255071801", "01992829122"],
  },
  {
    "email": "harunur.ibne@gguide.com",
    "hospital_name": "Ibne Sina Hospital Dhaka (Mirpur)",
    "role": "doctor",
    "name": "Harunur Rashid",
    "gender": "male",
    "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1723475421/glucoguide/doctors/doctor_male_8.jpg",
    "address": "Hazi Road, Shiyalbari Moor, 2 Avenue-03, Mirpur-02, Dhaka-1216",
    "created_by": "seeding",
    "description": "Diabetologist with expertise in lifestyle modification and weight management.",
    "available_times": "Tue, Thu: 10 AM - 2 PM",
    "experience": 5,
    "emails": ["info@ibnsinahospital.com", "support@ibnsinahospital.com"],
    "contact_numbers": ["+880256048222", "+8801675227777", "01312323232"],
  },
  {
    "email": "nazneen.mugda@gguide.com",
    "hospital_name": "Mugda Medical College & Hospital",
    "role": "doctor",
    "name": "Nazneen Ahmed",
    "gender": "female",
    "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1723475421/glucoguide/doctors/doctor_female_8.jpg",
    "address": "Hazi Kadam Ali Road, Mugda, Dhaka-1214",
    "created_by": "seeding",
    "description": "Senior Endocrinologist focusing on childhood diabetes.",
    "available_times": "Mon, Wed, Sat: 12 PM - 4 PM",
    "experience": 4,
    "emails": ["contact@mdchdhaka.com", "nazneen.mugda@gguide.com"],
    "contact_numbers": ["+88029676035", "01886464732"],
  },
  {
    "email": "shahidul.bdgh@gguide.com",
    "hospital_name": "Badda General Hospital",
    "role": "doctor",
    "name": "Shahidul Islam",
    "gender": "male",
    "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1723475421/glucoguide/doctors/doctor_male_9.jpg",
    "address": "107/2, Uttar Badda, Progoti Sarani, Dhaka-1212",
    "created_by": "seeding",
    "description": "Diabetes and Endocrinology specialist with a focus on geriatric diabetes.",
    "available_times": "Mon, Thu: 10 AM - 1 PM",
    "experience": 7,
    "emails": ["info@bdgh.org", "admin@bdgh.org", "shahidul.bdgh@gguide.com"],
    "contact_numbers": ["+88029131515", "+88029145729", "01924826822"],
  },
  {
    "email": "jannatul.impulse@gguide.com",
    "hospital_name": "Impulse Hospital",
    "role": "doctor",
    "name": "Jannatul Ferdous",
    "gender": "female",
    "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1723475421/glucoguide/doctors/doctor_female_9.jpg",
    "address": "304/E Shaheed Tazuddin Avenue,Tejgaon, Dhaka-1215",
    "created_by": "seeding",
    "description": "Experienced Diabetologist focusing on women’s health and diabetes.",
    "available_times": "Sun, Tue, Thu: 3 PM - 7 PM",
    "experience": 8,
    "emails": ["info@impulse.org"],
    "contact_numbers": ["+880258155672", "01988678782"],
  },
  {
    "email": "anwar.addin@gguide.com",
    "hospital_name": "Addin Medical College Hospital",
    "role": "doctor",
    "name": "Anwar Hossain",
    "gender": "male",
    "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1723475421/glucoguide/doctors/doctor_male_10.jpg",
    "address": "2 Bara Maghbazar, Outer Circular Road, Dhaka-1217",
    "created_by": "seeding",
    "description": "Specialist in Diabetes and Thyroid disorders.",
    "available_times": "Sat, Mon: 4 PM - 8 PM",
    "experience": 5,
    "emails": ["info@addinhospital.com", "anwar.addin@gguide.com"],
    "contact_numbers": ["+88028311515", "01718459911"],
  },
  {
    "email": "salma.farazy@gguide.com",
    "hospital_name": "Farazy Hospital",
    "role": "doctor",
    "name": "Salma Parveen",
    "gender": "female",
    "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1723475421/glucoguide/doctors/doctor_female_10.jpg",
    "address": "House-15, Block-E, Rampura, Dhaka-1219",
    "created_by": "seeding",
    "description": "Diabetes specialist with a focus on maternal diabetes.",
    "available_times": "Mon, Wed: 10 AM - 2 PM",
    "experience": 6,
    "emails": ["info@farazy.org", "salma.farazy@gguide.com"],
    "contact_numbers": ["+880258145923", "01819488120"],
  },
  {
    "email": "abir.popular@gguide.com",
    "hospital_name": "Popular Diagnostic Center (Uttara)",
    "role": "doctor",
    "name": "Abir Shikder",
    "gender": "male",
    "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1723475421/glucoguide/doctors/doctor_male_11.jpg",
    "address": "House-25, Road-07, Sector-04, Jashim Uddin Moar, Uttara, Dhaka-1230",
    "created_by": "seeding",
    "description": "Endocrinologist with a focus on insulin therapy and diabetes education.",
    "available_times": "Mon, Wed: 9 AM - 1 PM",
    "experience": 8,
    "emails": ["contact@populardiagnostic.com", "abir.popular@gguide.com"],
    "contact_numbers": ["+880255071801", "01614899122"],
  },
]