patients_data = [
    {
        "email": "pinkman@gguide.com",
        "name": "Jessie Pinkman",
        "gender": "male",
        "role": "admin",
        "address": "Banani, Dhaka-1213",
        "profession": "Drug Lord",
        "date_of_birth": "05/05/1999",
        "contact_number": "999999999",
        "emergency_number": "999999999",
        "created_by": "seeding",
    },
    {
        "email": "walterwhite@gguide.com",
        "name": "Walter White",
        "gender": "male",
        "address": "Dhanmondi, Dhaka-1205",
        "profession": "Chemistry Teacher",
        "date_of_birth": "09/07/1959",
        "contact_number": "01714787281",
        "emergency_number": "01876263512",
        "created_by": "seeding",
    },
    {
        "email": "skylerwhite@gguide.com",
        "name": "Skyler White",
        "gender": "female",
        "address": "Gulshan, Dhaka-1212",
        "profession": "Accountant",
        "date_of_birth": "08/11/1967",
        "contact_number": "01987646745",
        "emergency_number": "01822334455",
        "created_by": "seeding",
    },
    {
        "email": "hankschrader@gguide.com",
        "name": "Hank Schrader",
        "gender": "male",
        "address": "Mirpur, Dhaka-1216",
        "profession": "DEA Agent",
        "date_of_birth": "04/18/1966",
        "contact_number": "01378782762",
        "emergency_number": "01912763662",
        "created_by": "seeding",
    },
    {
        "email": "marieschrader@gguide.com",
        "name": "Marie Schrader",
        "gender": "female",
        "address": "Banani, Dhaka-1213",
        "profession": "Radiologic Technologist",
        "date_of_birth": "10/17/1968",
        "contact_number": "01714565454",
        "emergency_number": "01684646781",
        "created_by": "seeding",
    },
    {
        "email": "saulgoodman@gguide.com",
        "name": "Saul Goodman",
        "gender": "male",
        "address": "Mohakhali, Dhaka-1212",
        "profession": "Lawyer",
        "date_of_birth": "11/12/1960",
        "contact_number": "01616872101",
        "emergency_number": "01746867091",
        "created_by": "seeding",
    },
    {
        "email": "gustavofring@gguide.com",
        "name": "Gustavo Fring",
        "gender": "male",
        "address": "Uttara, Dhaka-1230",
        "profession": "Businessman",
        "date_of_birth": "06/23/1963",
        "contact_number": "01993131521",
        "emergency_number": "01934289767",
        "created_by": "seeding",
    },
    {
        "email": "mikeehrmantraut@gguide.com",
        "name": "Mike Ehrmantraut",
        "gender": "male",
        "address": "Bashundhara, Dhaka-1229",
        "profession": "Private Investigator",
        "date_of_birth": "02/06/1944",
        "contact_number": "01714687691",
        "emergency_number": "01888467181",
        "created_by": "seeding",
    },
    {
        "email": "lydiasharp@gguide.com",
        "name": "Lydia Sharp",
        "gender": "female",
        "address": "Banasree, Dhaka-1219",
        "profession": "Executive",
        "date_of_birth": "03/29/1978",
        "contact_number": "01914578920",
        "emergency_number": "01912181931",
        "created_by": "seeding",
    },
    {
        "email": "toddalquist@gguide.com",
        "name": "Todd Alquist",
        "gender": "male",
        "address": "Baridhara, Dhaka-1212",
        "profession": "Lab Assistant",
        "date_of_birth": "11/11/1987",
        "contact_number": "01614698181",
        "emergency_number": "01883132761",
        "created_by": "seeding",
    },
    {
        "email": "janesmith@gguide.com",
        "name": "Jane Smith",
        "gender": "female",
        "address": "Shantinagar, Dhaka-1217",
        "profession": "Artist",
        "date_of_birth": "08/03/1990",
        "contact_number": "01614564721",
        "emergency_number": "01912444424",
        "created_by": "seeding",
    },
]

hospitals_data = [
    {
        "name": "Square Hospital Dhaka",
        "address": "18/F, West Panthapath",
        "city": "Panthapath",
        "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1725012552/glucoguide/hospitals/square-hospital.jpg",
        "description": "Square Hospital is a leading private hospital in Dhaka known for its specialized care and state-of-the-art facilities.",
        "emails": ["contact@squarehospital.com", "support@squarehospital.com"],
        "contact_numbers": ["+88028214111", "+88029676767"],
        "geometry": {
            "coordinates": [90.381673, 23.7530335],
            "type": "Point",
        },
    },
    {
        "name": "Evercare Hospital Dhaka",
        "address": "Plot 81, Block-E, Bashundhara, Dhaka-1229",
        "city": "Bashundhara",
        "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1725012552/glucoguide/hospitals/evercare-hospital.jpg",
        "description": "Apollo Hospitals Dhaka is a renowned multi-specialty hospital known for its advanced medical treatments and patient care.",
        "emails": ["appointment@evercaredhaka.com", "info@evercaredhaka.com"],
        "contact_numbers": ["+880248008000", "+8801787685678"],
        "geometry": {
            "coordinates": [90.43126960143593, 23.809932148541805],
            "type": "Point",
        },
    },
    {
        "name": "Anwar Khan Modern Hospital Dhaka",
        "address": "House-17, Road-8,Dhanmondi, Dhaka-1207",
        "city": "Dhanmondi",
        "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1725012552/glucoguide/hospitals/anwar-hospital.jpg",
        "description": "Anwar Khan Modern Hospital is a dedicated facility for cardiac care, offering advanced treatments and surgery.",
        "emails": ["info@anwarkhanhospital.org", "appointment@anwarkhanhospital.org"],
        "contact_numbers": ["+88029166663", "+88029150394"],
        "geometry": {
            "coordinates": [90.382087, 23.74531],
            "type": "Point",
        },
    },
    {
        "name": "United Hospital Limited",
        "address": "Plot-15, Road-71, Gulshan-2, Dhaka-1212",
        "city": "Gulshan",
        "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1725012552/glucoguide/hospitals/united-hospital.jpg",
        "description": "United Hospital provides comprehensive healthcare services with a focus on cardiology, oncology, and emergency care.",
        "emails": ["info@uhlbd.com"],
        "contact_numbers": ["+880258150000"],
        "geometry": {
            "coordinates": [90.415832, 23.804858],
            "type": "Point",
        },
    },
    {
        "name": "Ibne Sina Hospital Dhaka (Dhanmondi)",
        "address": "House No. 70, Road-15/A, Dhanmondi, Dhaka-1209",
        "city": "Dhanmondi",
        "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1725012552/glucoguide/hospitals/ibn-sina-hospital.jpg",
        "description": "Ibne Sina Hospital provides a range of healthcare services with a focus on patient satisfaction and quality care.",
        "emails": ["info@ibnsinahospital.com", "support@ibnsinahospital.com"],
        "contact_numbers": ["+880258048321", "+8801675119999"],
        "geometry": {
            "coordinates": [90.37276, 23.745001],
            "type": "Point",
        },
    },
    {
        "name": "Labaid Specialized Hospital (Dhanmondi)",
        "address": "House-1, Road-4, Dhanmondi Dhaka-1205",
        "city": "Dhanmondi",
        "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1725012552/glucoguide/hospitals/labaid-hospital.jpg",
        "description": "Labaid Hospital Dhaka is a leading healthcare provider in the country, known for its excellence in cardiology and surgery.",
        "emails": ["info@labaidhospital.com", "support@labaidhospital.com"],
        "contact_numbers": ["+88029677885", "+8801755566222"],
        "geometry": {
            "coordinates": [90.383135, 23.741687499999998],
            "type": "Point",
        },
    },
    {
        "name": "Labaid Specialized Hospital (Gulshan)",
        "address": "House-13/A, Road-35, Gulshan-2, Dhaka-1212",
        "city": "Gulshan",
        "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1725012552/glucoguide/hospitals/labaid-hospital.jpg",
        "description": "Labaid Hospital Dhaka is a leading healthcare provider in the country, known for its excellence in cardiology and surgery.",
        "emails": ["info@labaidhospital.com", "support@labaidhospital.com"],
        "contact_numbers": ["+88029666825", "+8801755611222"],
        "geometry": {
            "coordinates": [90.412907, 23.794089],
            "type": "Point",
        },
    },
    {
        "name": "Popular Diagnostic Center (Dhanmondi)",
        "address": "House-16, Road-2, Dhanmondi, Dhaka-1205",
        "city": "Dhanmondi",
        "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1725012552/glucoguide/hospitals/popular-hospital.jpg",
        "description": "Popular Diagnostic Centre is a prominent medical diagnostic and healthcare service provider in Dhaka.",
        "emails": ["contact@populardiagnostic.com"],
        "contact_numbers": ["+880255071801"],
        "geometry": {
            "coordinates": [90.381667, 23.739226],
            "type": "Point",
        },
    },
    {
        "name": "Popular Diagnostic Center (Uttara)",
        "address": "House-25, Road-07, Sector-04, Jashim Uddin Moar, Uttara, Dhaka-1230",
        "city": "Uttara",
        "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1725012552/glucoguide/hospitals/popular-hospital.jpg",
        "description": "Popular Diagnostic Centre is a prominent medical diagnostic and healthcare service provider in Dhaka.",
        "emails": ["contact@populardiagnostic.com"],
        "contact_numbers": ["+880255071801"],
        "geometry": {
            "coordinates": [90.400331, 23.860908],
            "type": "Point",
        },
    },
    {
        "name": "Ibne Sina Hospital Dhaka (Mirpur)",
        "address": "Hazi Road, Shiyalbari Moor, 2 Avenue-03, Mirpur-02, Dhaka-1216",
        "city": "Mirpur",
        "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1725012552/glucoguide/hospitals/ibn-sina-hospital.jpg",
        "description": "Ibne Sina Hospital provides a range of healthcare services with a focus on patient satisfaction and quality care.",
        "emails": ["info@ibnsinahospital.com", "support@ibnsinahospital.com"],
        "contact_numbers": ["+880256048222", "+8801675227777"],
        "geometry": {
            "coordinates": [90.3622604597759, 23.77844844009768],
            "type": "Point",
        },
    },
    {
        "name": "Dhaka Medical College",
        "address": "Secretariat Road, Shahbag, Dhaka-1000",
        "city": "Ramna",
        "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1725012552/glucoguide/hospitals/dhaka-medical.jpg",
        "description": "Dhaka Medical College Hospital is one of the largest public hospitals in Bangladesh, offering a wide range of healthcare services.",
        "emails": ["info@dmch.gov.bd"],
        "contact_numbers": ["+88029551156"],
        "geometry": {
            "coordinates": [90.3975835, 23.7257475],
            "type": "Point",
        },
    },
    {
        "name": "Birdem General Hospital",
        "address": "122 Kazi Nazrul Islam Avenue, Shahbag, Dhaka-1000",
        "city": "Ramna",
        "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1725012552/glucoguide/hospitals/birdem-hospital.jpg",
        "description": "BIRDEM General Hospital specializes in diabetes care and is one of the most respected institutions in Dhaka.",
        "emails": ["info@birdemhospital.org"],
        "contact_numbers": ["+88029557791"],
        "geometry": {
            "coordinates": [90.396719, 23.73925],
            "type": "Point",
        },
    },
    {
        "name": "Holy Family Red Crescent Medical College",
        "address": "1 Eskatan Garden Road, Ramna, Dhaka-1000",
        "city": "Ramna",
        "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1725012552/glucoguide/hospitals/red-crescent-hospital.jpg",
        "description": "Holy Family Red Crescent Medical College Hospital offers comprehensive healthcare services with a focus on medical education.",
        "emails": ["info@hfrcmch.com", "admission@hfrcmch.com"],
        "contact_numbers": ["+88029348602", "+8801552015666"],
        "geometry": {
            "coordinates": [90.401716, 23.746023],
            "type": "Point",
        },
    },
    {
        "name": "Mugda Medical College & Hospital",
        "address": "Hazi Kadam Ali Road, Mugda, Dhaka-1214",
        "city": "Mugda",
        "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1725012552/glucoguide/hospitals/mugda-hospital.jpg",
        "description": "Mugda Medical College & Hospital is a well-known private hospital in Dhaka offering a wide range of medical services.",
        "emails": ["contact@mdchdhaka.com"],
        "contact_numbers": ["+88029676035"],
        "geometry": {
            "coordinates": [90.430053, 23.732472],
            "type": "Point",
        },
    },
    {
        "name": "Badda General Hospital",
        "address": "107/2, Uttar Badda, Progoti Sarani, Dhaka-1212",
        "city": "Gulshan",
        "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1725012552/glucoguide/hospitals/badda-hospital.jpg",
        "description": "Badda General Hospital is a private hospital providing healthcare services and medical education.",
        "emails": ["info@bdgh.org", "admin@bdgh.org"],
        "contact_numbers": ["+88029131515", "+88029145729"],
        "geometry": {
            "coordinates": [90.425663, 23.784485],
            "type": "Point",
        },
    },
    {
        "name": "Impulse Hospital",
        "address": "304/E Shaheed Tazuddin Avenue,Tejgaon, Dhaka-1215",
        "city": "Tejgaon",
        "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1725012552/glucoguide/hospitals/impulse-hospital.jpg",
        "description": "Impulse Hospital is a specialized hospital focusing on diabetes care and research.",
        "emails": ["info@impulse.org"],
        "contact_numbers": ["+880258155672"],
        "geometry": {
            "coordinates": [90.398749, 23.767836],
            "type": "Point",
        },
    },
    {
        "name": "Addin Medical College Hospital",
        "address": "2 Bara Maghbazar, Outer Circular Road, Dhaka-1217",
        "city": "Ramna",
        "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1725012552/glucoguide/hospitals/addin-medical.jpg",
        "description": "Ad-Din Hospital offers affordable healthcare services and is known for its maternal and child healthcare programs.",
        "emails": ["info@addinhospital.com"],
        "contact_numbers": ["+88028311515"],
        "geometry": {
            "coordinates": [90.405218, 23.748836],
            "type": "Point",
        },
    },
    {
        "name": "Farazy Hospital",
        "address": "House-15, Block-E, Rampura, Dhaka-1219",
        "city": "Rampura",
        "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1725012552/glucoguide/hospitals/farazy-hospital.jpg",
        "description": "Farazy Hospital provides affordable healthcare services to the underserved population of Dhaka.",
        "emails": ["info@farazy.org"],
        "contact_numbers": ["+880258145923"],
        "geometry": {
            "coordinates": [90.436169, 23.762542],
            "type": "Point",
        },
    },
    {
        "name": "Famous Specialized Hospital",
        "address": "House-05, Block-H, Block-E, Rampura, Dhaka-1219",
        "city": "Ramna",
        "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1725012552/glucoguide/hospitals/famous-hospital.jpg",
        "description": "Famous Specialized Hospital is a leading diabetes treatment facility in Dhaka with state-of-the-art technology.",
        "emails": ["info@famous.org", "diabetes@famous.org"],
        "contact_numbers": ["+880258167500", "+880258167501"],
        "geometry": {
            "coordinates": [90.44344942826072, 23.762023795255956],
            "type": "Point",
        },
    },
    {
        "name": "Central Basabo General Hospital",
        "address": "127, Central Basabo, Central Bashabo, Sobujbag, Dhaka-1214",
        "city": "Basabo",
        "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1725012552/glucoguide/hospitals/basabo-hospital.jpg",
        "description": "Central Basabo General Hospital is one of the oldest hospitals in Dhaka, offering a variety of healthcare services.",
        "emails": ["info@cbgh.org", "contact@info@cbgh.org"],
        "contact_numbers": ["+88029679295", "+88029670266"],
        "geometry": {
            "coordinates": [90.43456630089332, 23.740817551235864],
            "type": "Point",
        },
    },
]

doctors_data = [
    {
        "email": "habib.sqaure@gguide.com",
        "role": "doctor",
        "name": "Ahsan Habib",
        "gender": "male",
        "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1723475421/glucoguide/doctors/doctor_male_1.jpg",
        "address": "Dhanmondi, Dhaka-1205",
        "created_by": "seeding",
        "description": "Specialist in Diabetes and Endocrinology with 15 years of experience.",
        "hospital_name": "Square Hospital Dhaka",
        "available_times": "Mon, Wed, Fri: 10 AM - 8 PM",
        "experience": 5,
        "emails": [
            "contact@squarehospital.com",
            "support@squarehospital.com",
            "habib.sqaure@gguide.com",
        ],
        "contact_numbers": ["+88028214111", "+88029676767", "01376263512"],
    },
    {
        "email": "nusrat.evercare@gguide.com",
        "role": "doctor",
        "name": "Nusrat Jahan",
        "gender": "female",
        "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1723475421/glucoguide/doctors/doctor_female_1.jpg",
        "address": "Plot 81, Block-E, Bashundhara, Dhaka-1229",
        "created_by": "seeding",
        "description": "Renowned Diabetologist, focusing on Type 2 Diabetes management.",
        "hospital_name": "Evercare Hospital Dhaka",
        "available_times": "Tue, Thu, Sat: 9 AM - 9 PM",
        "experience": 6,
        "emails": [
            "appointment@evercaredhaka.com",
            "info@evercaredhaka.com",
            "nustrat.evercare@gguide.com",
        ],
        "contact_numbers": ["+880248008000", "+8801787685678", "01982345741"],
    },
    {
        "email": "moinul.united@gguide.com",
        "role": "doctor",
        "name": "Moinul Islam",
        "gender": "male",
        "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1723475421/glucoguide/doctors/doctor_male_2.jpg",
        "address": "Plot-15, Road-71, Gulshan-2, Dhaka-1212",
        "created_by": "seeding",
        "description": "Endocrinologist with a special interest in pediatric diabetes.",
        "hospital_name": "United Hospital Limited",
        "available_times": "Mon, Thu: 2 PM - 6 PM",
        "experience": 10,
        "emails": ["info@uhlbd.com", "moinul.united@gguide.com"],
        "contact_numbers": ["+880258150000", "01833332132"],
    },
    {
        "email": "tahmina.ibne@gguide.com",
        "role": "doctor",
        "name": "Tahmina Akter",
        "gender": "female",
        "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1723475421/glucoguide/doctors/doctor_female_2.jpg",
        "address": "House No. 70, Road-15/A, Dhanmondi, Dhaka-1209",
        "created_by": "seeding",
        "description": "Expert in gestational diabetes and diabetic foot care.",
        "hospital_name": "Ibne Sina Hospital Dhaka (Dhanmondi)",
        "available_times": "Sat, Sun: 11 AM - 3 PM",
        "experience": 8,
        "emails": [
            "info@ibnsinahospital.com",
            "support@ibnsinahospital.com",
            "tahmina.ibne@gguide.com",
        ],
        "contact_numbers": ["+880258048321", "+8801675119999", "01921120120"],
    },
    {
        "email": "rafiq.labaid@gguide.com",
        "role": "doctor",
        "name": "Rafiq Azad",
        "gender": "male",
        "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1723475421/glucoguide/doctors/doctor_male_3.jpg",
        "address": "House-1, Road-4, Dhanmondi Dhaka-1205",
        "created_by": "seeding",
        "description": "Diabetologist with 20 years of experience in treating Type 1 and Type 2 Diabetes.",
        "hospital_name": "Labaid Specialized Hospital (Dhanmondi)",
        "available_times": "Mon, Wed, Fri: 4 PM - 8 PM",
        "experience": 12,
        "emails": [
            "info@labaidhospital.com",
            "support@labaidhospital.com",
            "rafiq.labaid@gguide.com",
        ],
        "contact_numbers": ["+88029677885", "+8801755566222", "8801932121912"],
    },
    {
        "email": "sumaiya.popular@gguide.com",
        "role": "doctor",
        "name": "Sumaiya Alam",
        "gender": "female",
        "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1723475421/glucoguide/doctors/doctor_female_3.jpg",
        "address": "House-16, Road-2, Dhanmondi, Dhaka-1205",
        "created_by": "seeding",
        "description": "Specializes in diabetes-related complications and prevention.",
        "hospital_name": "Popular Diagnostic Center (Dhanmondi)",
        "available_times": "Tue, Thu, Sat: 10 AM - 2 PM",
        "experience": 7,
        "emails": ["contact@populardiagnostic.com", "sumaiya.popular@gguide.com"],
        "contact_numbers": ["+880255071801", "01782462710"],
    },
    {
        "email": "abul.popular@gguide.com",
        "hospital_name": "Dhaka Medical College",
        "role": "doctor",
        "name": "Abul Hossain",
        "gender": "male",
        "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1723475421/glucoguide/doctors/doctor_male_4.jpg",
        "address": "Secretariat Road, Shahbag, Dhaka-1000",
        "created_by": "seeding",
        "description": "Endocrinologist with a focus on insulin therapy and diabetes education.",
        "available_times": "Mon, Wed: 9 AM - 1 PM",
        "experience": 8,
        "emails": ["info@dmch.gov.bd", "abul.popular@gguide.com"],
        "contact_numbers": ["+88029551156", "01618977886"],
    },
    {
        "email": "farhana.birdem@gguide.com",
        "hospital_name": "Birdem General Hospital",
        "role": "doctor",
        "name": "Farhana Khan",
        "gender": "female",
        "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1723475421/glucoguide/doctors/doctor_female_4.jpg",
        "address": "122 Kazi Nazrul Islam Avenue, Shahbag, Dhaka-1000",
        "created_by": "seeding",
        "description": "Expert in managing complex cases of diabetes with co-existing conditions.",
        "available_times": "Sun, Tue, Thu: 2 PM - 6 PM",
        "experience": 4,
        "emails": ["info@birdemhospital.org", "farhana.birdem@gguide.com"],
        "contact_numbers": ["+88029557791", "01913488992"],
    },
    {
        "email": "zahir.holy@gguide.com",
        "hospital_name": "Holy Family Red Crescent Medical College",
        "role": "doctor",
        "name": "Zahir Uddin",
        "gender": "male",
        "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1723475421/glucoguide/doctors/doctor_male_5.jpg",
        "address": "1 Eskatan Garden Road, Ramna, Dhaka-1000",
        "created_by": "seeding",
        "description": "Diabetes specialist with a focus on diet and lifestyle management.",
        "available_times": "Mon, Fri: 3 PM - 7 PM",
        "experience": 5,
        "emails": [
            "info@hfrcmch.com",
            "admission@hfrcmch.com",
            "zahir.holy@gguide.com",
        ],
        "contact_numbers": ["+88029348602", "+8801552015666", "01761466672"],
    },
    {
        "email": "mahmuda.holy@gguide.com",
        "hospital_name": "Holy Family Red Crescent Medical College",
        "role": "doctor",
        "name": "Mahmuda Begum",
        "gender": "female",
        "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1723475421/glucoguide/doctors/doctor_female_5.jpg",
        "address": "1 Eskatan Garden Road, Ramna, Dhaka-1000",
        "created_by": "seeding",
        "description": "Senior Diabetologist with expertise in long-term diabetes care.",
        "available_times": "Tue, Thu: 10 AM - 1 PM",
        "experience": 10,
        "emails": [
            "info@hfrcmch.com",
            "admission@hfrcmch.com",
            "mahmuda.holy@gguide.com",
        ],
        "contact_numbers": ["+88029348602", "+8801552015666", "01922266688"],
    },
    {
        "email": "mahbubur.labid@gguide.com",
        "hospital_name": "Labaid Specialized Hospital (Gulshan)",
        "role": "doctor",
        "name": "Mahbubur Rahman",
        "gender": "female",
        "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1723475421/glucoguide/doctors/doctor_male_6.jpg",
        "address": "House-13/A, Road-35, Gulshan-2, Dhaka-1212",
        "created_by": "seeding",
        "description": "Specialist in Diabetes Mellitus and Metabolic Disorders.",
        "available_times": "Mon, Wed, Sat: 5 PM - 9 PM",
        "experience": 6,
        "emails": [
            "info@labaidhospital.com",
            "support@labaidhospital.com",
            "mahbubur.labid@gguide.com",
        ],
        "contact_numbers": ["+88029666825", "+8801755611222", "01884424242"],
    },
    {
        "email": "shahnaz.anwar@gguide.com",
        "hospital_name": "Anwar Khan Modern Hospital Dhaka",
        "role": "doctor",
        "name": "Shahnaz Huda",
        "gender": "female",
        "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1723475421/glucoguide/doctors/doctor_female_6.jpg",
        "address": "House-17, Road-8, Dhanmondi, Dhaka-1207",
        "created_by": "seeding",
        "description": "Diabetes expert with a focus on patient education and self-management.",
        "available_times": "Tue, Thu, Sun: 3 PM - 7 PM",
        "experience": 9,
        "emails": ["info@anwarkhanhospital.org", "appointment@anwarkhanhospital.org"],
        "contact_numbers": ["+88029166663", "+88029150394", "01718999202"],
    },
    {
        "email": "rezaul.labaid@gguide.com",
        "hospital_name": "Labaid Specialized Hospital",
        "role": "doctor",
        "name": "Rezaul Karim",
        "gender": "male",
        "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1723475421/glucoguide/doctors/doctor_male_7.jpg",
        "address": "House-13/A, Road-35, Gulshan-2, Dhaka-1212",
        "created_by": "seeding",
        "description": "Experienced Diabetologist specializing in insulin pump therapy.",
        "available_times": "Mon, Fri: 11 AM - 3 PM",
        "experience": 14,
        "emails": [
            "info@labaidhospital.com",
            "support@labaidhospital.com",
            "rezaul.labaid@gguide.com",
        ],
        "contact_numbers": ["+88029666825", "+8801755611222", "01912182280"],
    },
    {
        "email": "samira.popular@gguide.com",
        "hospital_name": "Popular Diagnostic Center (Uttara)",
        "role": "doctor",
        "name": "Samira Haque",
        "gender": "female",
        "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1723475421/glucoguide/doctors/doctor_female_7.jpg",
        "address": "House-25, Road-07, Sector-04, Jashim Uddin Moar, Uttara, Dhaka-1230",
        "created_by": "seeding",
        "description": "Specializes in the prevention and management of diabetes complications.",
        "available_times": "Mon, Wed: 2 PM - 6 PM",
        "experience": 6,
        "emails": ["contact@populardiagnostic.com", "samira.popular@gguide.com"],
        "contact_numbers": ["+880255071801", "01992829122"],
    },
    {
        "email": "harunur.ibne@gguide.com",
        "hospital_name": "Ibne Sina Hospital Dhaka (Mirpur)",
        "role": "doctor",
        "name": "Harunur Rashid",
        "gender": "male",
        "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1723475421/glucoguide/doctors/doctor_male_8.jpg",
        "address": "Hazi Road, Shiyalbari Moor, 2 Avenue-03, Mirpur-02, Dhaka-1216",
        "created_by": "seeding",
        "description": "Diabetologist with expertise in lifestyle modification and weight management.",
        "available_times": "Tue, Thu: 10 AM - 2 PM",
        "experience": 5,
        "emails": ["info@ibnsinahospital.com", "support@ibnsinahospital.com"],
        "contact_numbers": ["+880256048222", "+8801675227777", "01312323232"],
    },
    {
        "email": "nazneen.mugda@gguide.com",
        "hospital_name": "Mugda Medical College & Hospital",
        "role": "doctor",
        "name": "Nazneen Ahmed",
        "gender": "female",
        "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1723475421/glucoguide/doctors/doctor_female_8.jpg",
        "address": "Hazi Kadam Ali Road, Mugda, Dhaka-1214",
        "created_by": "seeding",
        "description": "Senior Endocrinologist focusing on childhood diabetes.",
        "available_times": "Mon, Wed, Sat: 12 PM - 4 PM",
        "experience": 4,
        "emails": ["contact@mdchdhaka.com", "nazneen.mugda@gguide.com"],
        "contact_numbers": ["+88029676035", "01886464732"],
    },
    {
        "email": "shahidul.bdgh@gguide.com",
        "hospital_name": "Badda General Hospital",
        "role": "doctor",
        "name": "Shahidul Islam",
        "gender": "male",
        "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1723475421/glucoguide/doctors/doctor_male_9.jpg",
        "address": "107/2, Uttar Badda, Progoti Sarani, Dhaka-1212",
        "created_by": "seeding",
        "description": "Diabetes and Endocrinology specialist with a focus on geriatric diabetes.",
        "available_times": "Mon, Thu: 10 AM - 1 PM",
        "experience": 7,
        "emails": ["info@bdgh.org", "admin@bdgh.org", "shahidul.bdgh@gguide.com"],
        "contact_numbers": ["+88029131515", "+88029145729", "01924826822"],
    },
    {
        "email": "jannatul.impulse@gguide.com",
        "hospital_name": "Impulse Hospital",
        "role": "doctor",
        "name": "Jannatul Ferdous",
        "gender": "female",
        "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1723475421/glucoguide/doctors/doctor_female_9.jpg",
        "address": "304/E Shaheed Tazuddin Avenue,Tejgaon, Dhaka-1215",
        "created_by": "seeding",
        "description": "Experienced Diabetologist focusing on women’s health and diabetes.",
        "available_times": "Sun, Tue, Thu: 3 PM - 7 PM",
        "experience": 8,
        "emails": ["info@impulse.org"],
        "contact_numbers": ["+880258155672", "01988678782"],
    },
    {
        "email": "anwar.addin@gguide.com",
        "hospital_name": "Addin Medical College Hospital",
        "role": "doctor",
        "name": "Anwar Hossain",
        "gender": "male",
        "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1723475421/glucoguide/doctors/doctor_male_10.jpg",
        "address": "2 Bara Maghbazar, Outer Circular Road, Dhaka-1217",
        "created_by": "seeding",
        "description": "Specialist in Diabetes and Thyroid disorders.",
        "available_times": "Sat, Mon: 4 PM - 8 PM",
        "experience": 5,
        "emails": ["info@addinhospital.com", "anwar.addin@gguide.com"],
        "contact_numbers": ["+88028311515", "01718459911"],
    },
    {
        "email": "salma.farazy@gguide.com",
        "hospital_name": "Farazy Hospital",
        "role": "doctor",
        "name": "Salma Parveen",
        "gender": "female",
        "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1723475421/glucoguide/doctors/doctor_female_10.jpg",
        "address": "House-15, Block-E, Rampura, Dhaka-1219",
        "created_by": "seeding",
        "description": "Diabetes specialist with a focus on maternal diabetes.",
        "available_times": "Mon, Wed: 10 AM - 2 PM",
        "experience": 6,
        "emails": ["info@farazy.org", "salma.farazy@gguide.com"],
        "contact_numbers": ["+880258145923", "01819488120"],
    },
    {
        "email": "abir.popular@gguide.com",
        "hospital_name": "Popular Diagnostic Center (Uttara)",
        "role": "doctor",
        "name": "Abir Shikder",
        "gender": "male",
        "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1723475421/glucoguide/doctors/doctor_male_7.jpg",
        "address": "House-25, Road-07, Sector-04, Jashim Uddin Moar, Uttara, Dhaka-1230",
        "created_by": "seeding",
        "description": "Endocrinologist with a focus on insulin therapy and diabetes education.",
        "available_times": "Mon, Wed: 9 AM - 1 PM",
        "experience": 8,
        "emails": ["contact@populardiagnostic.com", "abir.popular@gguide.com"],
        "contact_numbers": ["+880255071801", "01614899122"],
    },
]


meals_data = [
    {
        "name": "Greek Yogurt Parfait",
        "category": "breakfast",
        "description": "Creamy Greek yogurt layered with fresh berries, honey, and granola.",
        "ingredients": ["yogurt", "berries", "honey", "granola", "sugar", "fruits"],
        "time": "10-15mins",
        "calories": 298,
        "protein": 21,
        "fat": 11,
        "carbs": 28,
        "blog": "https://foolproofliving.com/layered-yogurt-parfait",
        "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1720442441/glucoguide/meals/breakfast-1.jpg",
        "cuisine": "Greek",
    },
    {
        "name": "Avocado Toast",
        "category": "breakfast",
        "description": "Whole grain toast topped with mashed avocado, salt, pepper, and a sprinkle of chili flakes.",
        "ingredients": [
            "grain",
            "avocado",
            "salt",
            "pepper",
            "refined-carbs",
            "vegetables",
        ],
        "time": "4-5mins",
        "calories": 180,
        "protein": 4.2,
        "fat": 13.6,
        "carbs": 15.5,
        "blog": "https://www.loveandlemons.com/avocado-toast-recipe/",
        "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1720442441/glucoguide/meals/breakfast-2.jpg",
        "cuisine": "American",
    },
    {
        "name": "Oatmeal with Fruits",
        "category": "breakfast",
        "description": "Warm oatmeal topped with banana slices, berries, and a drizzle of maple syrup.",
        "ingredients": [
            "oats",
            "banana",
            "berries",
            "syrup",
            "sugar",
            "milk",
            "dairy",
            "fruits",
        ],
        "cuisine": "American",
        "time": "8-10mins",
        "calories": 341,
        "protein": 22,
        "fat": 8,
        "carbs": 47,
        "blog": "https://www.eatingwell.com/recipe/251317/oatmeal-with-fruit-nuts/",
        "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1720442441/glucoguide/meals/breakfast-3.jpg",
    },
    {
        "name": "Breakfast Burrito",
        "category": "breakfast",
        "description": "A flour tortilla filled with scrambled eggs, cheese, and salsa.",
        "ingredients": ["flour", "eggs", "cheese", "salsa", "spices"],
        "cuisine": "Mexican",
        "time": "25-35mins",
        "calories": 534,
        "protein": 31,
        "fat": 36,
        "carbs": 29,
        "blog": "https://themodernproper.com/breakfast-burritos",
        "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1720442441/glucoguide/meals/breakfast-4.jpg",
    },
    {
        "name": "Smoothie Bowl",
        "category": "breakfast",
        "description": "A thick smoothie topped with fresh fruits, nuts, and seeds.",
        "cuisine": "American",
        "ingredients": [
            "banana",
            "berries",
            "spinach",
            "milk",
            "nuts",
            "seeds",
            "dairy",
            "fruits",
        ],
        "time": "5-8mins",
        "calories": 214,
        "protein": 2.8,
        "fat": 2.5,
        "carbs": 47.5,
        "blog": "https://minimalistbaker.com/favorite-smoothie-bowl-5-minutes/",
        "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1720442441/glucoguide/meals/breakfast-5.jpg",
    },
    {
        "name": "Eggs Benedict",
        "category": "breakfast",
        "description": "Poached eggs and ham on an English muffin, topped with hollandaise sauce.",
        "ingredients": ["eggs", "ham", "dairy"],
        "cuisine": "American",
        "time": "25-30mins",
        "calories": 348,
        "protein": 16,
        "fat": 24,
        "carbs": 15,
        "blog": "https://tastesbetterfromscratch.com/eggs-benedict-with-homemade-hollandaise-sauce/",
        "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1720442441/glucoguide/meals/breakfast-6.jpg",
    },
    {
        "name": "Pancakes with Maple Syrup",
        "category": "breakfast",
        "description": "Fluffy pancakes served with butter and maple syrup.",
        "ingredients": ["flour", "milk", "eggs", "butter", "sugar", "syrup", "dairy"],
        "cuisine": "American",
        "time": "20-30mins",
        "calories": 445,
        "protein": 13,
        "fat": 17,
        "carbs": 59,
        "blog": "https://www.tasteofhome.com/recipes/maple-pancakes/",
        "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1720442441/glucoguide/meals/breakfast-7.jpg",
    },
    {
        "name": "French Toast",
        "category": "breakfast",
        "description": "Slices of bread soaked in a mixture of eggs and milk, then fried and topped with powdered sugar.",
        "ingredients": ["bread", "eggs", "milk", "dairy"],
        "cuisine": "French",
        "time": "10-15mins",
        "calories": 100,
        "protein": 4,
        "fat": 3,
        "carbs": 11,
        "blog": "https://tastesbetterfromscratch.com/classic-french-toast/",
        "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1720442441/glucoguide/meals/breakfast-8.jpg",
    },
    {
        "name": "Bagel with Cream Cheese",
        "category": "breakfast",
        "description": "Toasted bagel spread with creamy cheese.",
        "ingredients": ["bagel", "dairy", "flour"],
        "cuisine": "American",
        "time": "5-8mins",
        "calories": 400,
        "protein": 13,
        "fat": 11,
        "carbs": 57,
        "blog": "https://www.melaniecooks.com/bagel-with-cream-cheese/5235/",
        "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1720442441/glucoguide/meals/breakfast-9.jpg",
    },
    {
        "name": "Muffins",
        "category": "breakfast",
        "description": "Freshly baked muffins with a variety of flavors such as blueberry, chocolate chip, or banana nut.",
        "ingredients": ["flour", "sugar", "eggs", "butter", "flavorings", "dairy"],
        "cuisine": "American",
        "time": "25-35mins",
        "calories": 519,
        "protein": 8,
        "fat": 20,
        "carbs": 80,
        "blog": "https://laneandgreyfare.com/chocolate-chip-blueberry-muffins/",
        "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1720442441/glucoguide/meals/breakfast-10.jpg",
    },
    {
        "name": "Caesar Salad",
        "category": "lunch",
        "description": "Crisp romaine lettuce, croutons, and Parmesan cheese, tossed with Caesar dressing.",
        "ingredients": ["lettuce", "croutons", "cheese", "vegetables"],
        "cuisine": "Italian",
        "time": "25-35mins",
        "calories": 300,
        "protein": 4,
        "fat": 26,
        "carbs": 9,
        "blog": "https://natashaskitchen.com/caesar-salad-recipe/",
        "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1720442441/glucoguide/meals/lunch-1.jpg",
    },
    {
        "name": "Grilled Chicken Sandwich",
        "category": "lunch",
        "description": "Grilled chicken breast on a bun with lettuce, tomato, and mayo.",
        "ingredients": [
            "chicken",
            "bun",
            "lettuce",
            "tomato",
            "refined-carbs",
            "vegetables",
        ],
        "cuisine": "American",
        "time": "15-25mins",
        "calories": 410,
        "protein": 45,
        "fat": 11.5,
        "carbs": 29.5,
        "blog": "https://www.skinnytaste.com/grilled-chicken-sandwich/",
        "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1720442441/glucoguide/meals/lunch-2.jpg",
    },
    {
        "name": "Vegetable Stir-Fry",
        "category": "lunch",
        "description": "A mix of vegetables stir-fried with soy sauce and served over rice.",
        "ingredients": [
            "broccoli",
            "corns",
            "carrots",
            "peppers",
            "soy-sauce",
            "rice",
            "refined-carbs" "vegetables",
        ],
        "cuisine": "Chinese",
        "time": "15-20mins",
        "calories": 152,
        "protein": 5,
        "fat": 4,
        "carbs": 27,
        "blog": "https://themodernproper.com/vegetable-stir-fry",
        "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1720442441/glucoguide/meals/lunch-3.jpg",
    },
    {
        "name": "Turkey Wrap",
        "category": "lunch",
        "description": "Sliced turkey, lettuce, tomato, and cheese wrapped in a tortilla.",
        "ingredients": ["flour", "turkey", "lettuce", "tomato", "cheese", "vegetables"],
        "cuisine": "American",
        "time": "10-15mins",
        "calories": 400,
        "protein": 24,
        "fat": 19,
        "carbs": 32,
        "blog": "https://www.twopeasandtheirpod.com/turkey-wrap/",
        "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1720442441/glucoguide/meals/lunch-4.jpg",
    },
    {
        "name": "Quinoa Salad",
        "category": "lunch",
        "description": "Quinoa mixed with cucumbers, tomatoes, and feta cheese, dressed with lemon vinaigrette.",
        "ingredients": [
            "quinoa",
            "cucumbers",
            "tomatoes",
            "cheese",
            "lemon",
            "vegetables",
        ],
        "cuisine": "American",
        "time": "25-30mins",
        "calories": 290,
        "protein": 8.8,
        "fat": 14,
        "carbs": 33,
        "blog": "https://www.inspiredtaste.net/38096/quinoa-salad-recipe/",
        "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1720442441/glucoguide/meals/lunch-5.jpg",
    },
    {
        "name": "Spaghetti Carbonara",
        "category": "lunch",
        "description": "Spaghetti tossed with a creamy sauce made from eggs, cheese, pancetta, and pepper.",
        "ingredients": ["spaghetti", "eggs", "cheese", "pancetta", "pepper"],
        "cuisine": "Italian",
        "time": "30-40mins",
        "calories": 535,
        "protein": 22,
        "fat": 20,
        "carbs": 64,
        "blog": "https://damndelicious.net/2014/03/29/spaghetti-carbonara/",
        "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1720442441/glucoguide/meals/lunch-6.jpg",
    },
    {
        "name": "Chicken Caesar Wrap",
        "category": "lunch",
        "description": "Grilled chicken, romaine lettuce, and Caesar dressing wrapped in a tortilla.",
        "ingredients": ["flour", "chicken", "lettuce"],
        "cuisine": "American",
        "time": "10-15mins",
        "calories": 400,
        "protein": 27,
        "fat": 19,
        "carbs": 28,
        "blog": "https://www.twopeasandtheirpod.com/chicken-caesar-wrap/",
        "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1720442441/glucoguide/meals/lunch-7.jpg",
    },
    {
        "name": "Caprese Sandwich",
        "category": "lunch",
        "description": "Mozzarella, tomatoes, and basil on ciabatta bread, drizzled with balsamic glaze.",
        "ingredients": ["bread", "cheese", "tomatoes", "basil", "vegetables"],
        "cuisine": "Italian",
        "time": "15-20mins",
        "calories": 376,
        "protein": 17,
        "fat": 16,
        "carbs": 42,
        "blog": "https://www.eatingwell.com/recipe/7944052/caprese-sandwich/",
        "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1720442441/glucoguide/meals/lunch-8.jpg",
    },
    {
        "name": "Tuna Salad",
        "category": "lunch",
        "description": "Tuna mixed with mayo, celery, and onions, served on a bed of lettuce.",
        "ingredients": ["tuna", "celery", "onions", "lettuce", "vegetables"],
        "cuisine": "American",
        "time": "15-20mins",
        "calories": 380,
        "protein": 17,
        "fat": 11,
        "carbs": 19,
        "blog": "https://downshiftology.com/recipes/tuna-salad/",
        "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1720442441/glucoguide/meals/lunch-9.jpg",
    },
    {
        "name": "Veggie Burger",
        "category": "lunch",
        "description": "A plant-based burger patty on a bun with lettuce, tomato, and avocado.",
        "ingredients": ["flour", "lettuce", "tomato", "avocado", "vegetables"],
        "cuisine": "American",
        "time": "30-45mins",
        "calories": 200,
        "protein": 8.3,
        "fat": 8,
        "carbs": 22.7,
        "blog": "https://www.inspiredtaste.net/36554/veggie-burger-recipe/",
        "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1720442441/glucoguide/meals/lunch-10.jpg",
    },
    {
        "name": "Hummus and Veggies",
        "category": "snacks",
        "description": "Creamy hummus served with carrot sticks, cucumber slices, and bell pepper strips.",
        "ingredients": [
            "hummus",
            "carrots",
            "cucumber",
            "bell-peppers",
            "vegetables",
            "refined-carbs",
        ],
        "cuisine": "Middle Eastern",
        "time": "15-20mins",
        "calories": 89,
        "protein": 3,
        "fat": 5,
        "carbs": 9,
        "blog": "https://www.thecookierookie.com/hummus-and-vegetable-board/",
        "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1720442441/glucoguide/meals/snacks-1.jpg",
    },
    {
        "name": "Apple Slices with Peanut Butter",
        "category": "snacks",
        "description": "Fresh apple slices dipped in creamy peanut butter.",
        "ingredients": ["apple", "peanut", "fruits"],
        "cuisine": "American",
        "time": "5mins",
        "calories": 282,
        "protein": 8.5,
        "fat": 16.4,
        "carbs": 31.4,
        "blog": "https://www.food.com/recipe/apples-and-peanut-butter-apple-slices-218390/",
        "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1720442441/glucoguide/meals/snacks-2.jpg",
    },
    {
        "name": "Cheese and Crackers",
        "category": "snacks",
        "description": "Assorted cheese slices served with whole grain crackers.",
        "ingredients": ["cheese", "jam", "grain", "dairy"],
        "cuisine": "American",
        "time": "5-10mins",
        "calories": 179,
        "protein": 3.8,
        "fat": 5.8,
        "carbs": 2.34,
        "blog": "https://eatwell101.com/low-carb-cheese-crackers-recipe",
        "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1720442441/glucoguide/meals/snacks-3.jpg",
    },
    {
        "name": "Trail Mix",
        "category": "snacks",
        "description": "A mix of nuts, dried fruits, and chocolate chips.",
        "ingredients": ["nuts", "fruits"],
        "cuisine": "American",
        "time": "10-15mins",
        "calories": 180,
        "protein": 4,
        "fat": 9,
        "carbs": 14,
        "blog": "https://www.thehealthymaven.com/how-to-build-a-healthy-trail-mix/",
        "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1720442441/glucoguide/meals/snacks-4.jpg",
    },
    {
        "name": "Yogurt and Granola",
        "category": "snacks",
        "description": "Creamy yogurt topped with crunchy granola.",
        "ingredients": ["yogurt", "granola", "dairy"],
        "cuisine": "American",
        "time": "8-10mins",
        "calories": 300,
        "protein": 22,
        "fat": 13,
        "carbs": 60,
        "blog": "https://www.jaroflemons.com/granola-breakfast-bowl/",
        "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1720442441/glucoguide/meals/snacks-5.jpg",
    },
    {
        "name": "Fruit Salad",
        "category": "snacks",
        "description": "A mix of fresh fruits such as strawberries, kiwis, melons, etc",
        "ingredients": [
            "strawberries",
            "oranges",
            "kiwis",
            "apples",
            "pomegranate",
            "fruits",
        ],
        "cuisine": "American",
        "time": "5-10mins",
        "calories": 155,
        "protein": 2,
        "fat": 1,
        "carbs": 39,
        "blog": "https://www.allrecipes.com/recipe/214947/perfect-summer-fruit-salad/",
        "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1720442441/glucoguide/meals/snacks-6.jpg",
    },
    {
        "name": "Popcorn",
        "category": "snacks",
        "description": "Lightly salted and buttered popcorn.",
        "ingredients": ["popcorn", "salt", "butter"],
        "cuisine": "American",
        "time": "10-15mins",
        "calories": 93,
        "protein": 3,
        "fat": 1.1,
        "carbs": 18.6,
        "blog": "https://cookieandkate.com/perfect-stovetop-popcorn-recipe/",
        "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1720442441/glucoguide/meals/snacks-7.jpg",
    },
    {
        "name": "Energy Balls",
        "category": "snacks",
        "description": "No-bake energy balls made with oats, peanut butter, and honey.",
        "ingredients": ["oats", "peanuts", "honey", "butter", "fruits"],
        "cuisine": "American",
        "time": "25-40mins",
        "calories": 131,
        "protein": 4,
        "fat": 5,
        "carbs": 18,
        "blog": "https://www.wellplated.com/energy-balls/",
        "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1720442441/glucoguide/meals/snacks-8.jpg",
    },
    {
        "name": "Veggie Chips",
        "category": "snacks",
        "description": "Crispy baked vegetable chips made from sweet potatoes and black pepper",
        "ingredients": ["potatoes", "black pepper", "beets", "kale", "vegetables"],
        "cuisine": "American",
        "time": "15-20mins",
        "calories": 99,
        "protein": 3,
        "fat": 1,
        "carbs": 22,
        "blog": "https://thebigmansworld.com/oil-free-baked-veggie-chips-paleo-vegan-gluten-free/",
        "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1720442441/glucoguide/meals/snacks-9.jpg",
    },
    {
        "name": "Protein Shake",
        "category": "snacks",
        "description": "A protein-rich shake made with protein powder, milk, and a banana.",
        "ingredients": ["milk", "banana", "yogurt", "grains"],
        "cuisine": "American",
        "time": "10-15mins",
        "calories": 282,
        "protein": 33,
        "fat": 8,
        "carbs": 23,
        "blog": "https://fitfoodiefinds.com/best-protein-shakes/",
        "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1720442441/glucoguide/meals/snacks-10.jpg",
    },
    {
        "name": "Mediterranean Salmon with Roasted Vegetables",
        "category": "dinner",
        "description": "Baked salmon with lemon, herbs, and tomatoes paired with roasted zucchini, peppers, and onions.",
        "ingredients": [
            "lemon",
            "herbs",
            "tomatoes",
            "salmon",
            "fish",
            "onion",
            "pepper",
            "zucchini",
            "vegetables",
        ],
        "cuisine": "Mediterranean",
        "time": "25-45mins",
        "calories": 485,
        "protein": 41.1,
        "fat": 18.8,
        "carbs": 11,
        "blog": "https://apriljharris.com/one-pan-salmon-and-mediterranean-vegetables/",
        "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1720442441/glucoguide/meals/dinner-1.jpg",
    },
    {
        "name": "Beef Tacos",
        "category": "dinner",
        "description": "Ground beef tacos served with lettuce, cheese, and salsa.",
        "ingredients": [
            "beef",
            "red meat",
            "taco shells",
            "lettuce",
            "cheese",
            "salsa",
            "refined-carbs",
            "vegetables",
        ],
        "cuisine": "Mexican",
        "time": "25-35mins",
        "calories": 293,
        "protein": 17,
        "fat": 14,
        "carbs": 24,
        "blog": "https://www.howsweeteats.com/2019/01/ground-beef-tacos/",
        "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1720442441/glucoguide/meals/dinner-2.jpg",
    },
    {
        "name": "Chicken Alfredo",
        "category": "dinner",
        "description": "Fettuccine pasta with creamy Alfredo sauce and grilled chicken.",
        "ingredients": ["fettuccine", "Alfredo sauce", "chicken", "refined-carbs"],
        "cuisine": "Italian",
        "time": "25-40mins",
        "calories": 756,
        "protein": 47,
        "fat": 42,
        "carbs": 46,
        "blog": "https://www.budgetbytes.com/chicken-alfredo/",
        "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1720442441/glucoguide/meals/dinner-3.jpg",
    },
    {
        "name": "Vegetarian Chili",
        "category": "dinner",
        "description": "A hearty chili made with beans, tomatoes, and a blend of spices.",
        "ingredients": ["beans", "tomatoes", "spices", "vegetables"],
        "cuisine": "American",
        "time": "25-40mins",
        "calories": 230,
        "protein": 11,
        "fat": 6.6,
        "carbs": 35,
        "blog": "https://cookieandkate.com/vegetarian-chili-recipe/",
        "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1720442441/glucoguide/meals/dinner-4.jpg",
    },
    {
        "name": "Stuffed Bell Peppers",
        "category": "dinner",
        "description": "Bell peppers stuffed with rice, ground beef, and vegetables, baked to perfection.",
        "ingredients": ["bell peppers", "rice", "beef", "red meat", "vegetables"],
        "cuisine": "American",
        "time": "40-50mins",
        "calories": 454,
        "protein": 18,
        "fat": 33,
        "carbs": 22,
        "blog": "https://www.budgetbytes.com/stuffed-bell-peppers/",
        "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1720442441/glucoguide/meals/dinner-5.jpg",
    },
    {
        "name": "Shrimp Scampi",
        "category": "dinner",
        "description": "Shrimp sautéed in garlic and butter, served over linguine.",
        "ingredients": ["shrimp", "garlic", "butter", "linguine", "fish"],
        "cuisine": "Italian",
        "time": "15-20mins",
        "calories": 325,
        "protein": 40,
        "fat": 14,
        "carbs": 3,
        "blog": "https://cooking.nytimes.com/recipes/9101-classic-shrimp-scampi",
        "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1720442441/glucoguide/meals/dinner-6.jpg",
    },
    {
        "name": "Creamy Lemon Chicken Piccata",
        "category": "dinner",
        "description": "Grilled chicken marinated in lemon and herbs, served with with pasta and a side of steamed vegetables.",
        "ingredients": ["chicken", "lemon", "herbs", "vegetables", "refined-carbs"],
        "cuisine": "Italian",
        "time": "50mins",
        "calories": 265,
        "protein": 37,
        "fat": 11,
        "carbs": 2,
        "blog": "https://www.allrecipes.com/recipe/9011/simple-lemon-herb-chicken/",
        "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1720442441/glucoguide/meals/dinner-7.jpg",
    },
    {
        "name": "Spaghetti Bolognese",
        "category": "dinner",
        "description": "Spaghetti with a rich and meaty Bolognese sauce.",
        "ingredients": [
            "spaghetti",
            "beef",
            "red meat",
            "tomato sauce",
            "onion",
            "garlic",
            "red meat",
            "refined-carbs",
        ],
        "cuisine": "Italian",
        "time": "20-30mins",
        "calories": 510,
        "protein": 40.9,
        "fat": 12.6,
        "carbs": 53.2,
        "blog": "https://www.recipetineats.com/spaghetti-bolognese/",
        "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1720442441/glucoguide/meals/dinner-8.jpg",
    },
    {
        "name": "Vegetable Lasagna",
        "category": "dinner",
        "description": "Lasagna layered with a variety of vegetables, ricotta cheese, and marinara sauce.",
        "ingredients": [
            "noodles",
            "vegetables",
            "cheese",
            "marinara sauce",
        ],
        "cuisine": "Italian",
        "time": "30-40mins",
        "calories": 335,
        "protein": 19.3,
        "fat": 8.5,
        "carbs": 42.2,
        "blog": "https://cookieandkate.com/best-vegetable-lasagna-recipe/",
        "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1720442441/glucoguide/meals/dinner-9.jpg",
    },
    {
        "name": "Beef Stroganoff",
        "category": "dinner",
        "description": "Tender beef in a creamy mushroom sauce, served over egg noodles.",
        "ingredients": ["beef", "red meat", "mushrooms", "cream", "eggs", "noodles"],
        "cuisine": "Italian",
        "time": "30-40mins",
        "calories": 586,
        "protein": 37,
        "fat": 44,
        "carbs": 9,
        "blog": "https://www.recipetineats.com/beef-stroganoff/",
        "img_src": "https://res.cloudinary.com/dwhlynqj3/image/upload/v1720442441/glucoguide/meals/dinner-10.jpg",
    },
]


dummy_suggestions = {
    "18-24": {
        "energy_goal": 2500,
        "hydration": "8",
        "sleep": "8 hours",
        "dietary": [
            {"time": "breakfast", "energy": 625},
            {"time": "lunch", "energy": 725},
            {"time": "snacks", "energy": 125},
            {"time": "dinner", "energy": 725},
        ],
        "nutritions": [
            {"name": "protein", "amount": 56},
            {"name": "fat", "amount": 80},
            {"name": "carbs", "amount": 300},
        ],
    },
    "25-34": {
        "energy_goal": 2400,
        "hydration": "8",
        "sleep": "7-8 hours",
        "dietary": [
            {"time": "breakfast", "energy": 600},
            {"time": "lunch", "energy": 700},
            {"time": "snacks", "energy": 120},
            {"time": "dinner", "energy": 680},
        ],
        "nutritions": [
            {"name": "protein", "amount": 55},
            {"name": "fat", "amount": 78},
            {"name": "carbs", "amount": 290},
        ],
    },
    "35-44": {
        "energy_goal": 2300,
        "hydration": "8",
        "sleep": "7-8 hours",
        "dietary": [
            {"time": "breakfast", "energy": 575},
            {"time": "lunch", "energy": 675},
            {"time": "snacks", "energy": 115},
            {"time": "dinner", "energy": 650},
        ],
        "nutritions": [
            {"name": "protein", "amount": 54},
            {"name": "fat", "amount": 76},
            {"name": "carbs", "amount": 285},
        ],
    },
    "45-54": {
        "energy_goal": 2200,
        "hydration": "8",
        "sleep": "7-8 hours",
        "dietary": [
            {"time": "breakfast", "energy": 550},
            {"time": "lunch", "energy": 650},
            {"time": "snacks", "energy": 110},
            {"time": "dinner", "energy": 620},
        ],
        "nutritions": [
            {"name": "protein", "amount": 52},
            {"name": "fat", "amount": 74},
            {"name": "carbs", "amount": 270},
        ],
    },
    "55-64": {
        "energy_goal": 2100,
        "hydration": "8",
        "sleep": "7-9 hours",
        "dietary": [
            {"time": "breakfast", "energy": 525},
            {"time": "lunch", "energy": 625},
            {"time": "snacks", "energy": 105},
            {"time": "dinner", "energy": 605},
        ],
        "nutritions": [
            {"name": "protein", "amount": 50},
            {"name": "fat", "amount": 72},
            {"name": "carbs", "amount": 260},
        ],
    },
    "65+": {
        "energy_goal": 2000,
        "hydration": "8",
        "sleep": "7-9 hours",
        "dietary": [
            {"time": "breakfast", "energy": 500},
            {"time": "lunch", "energy": 600},
            {"time": "snacks", "energy": 100},
            {"time": "dinner", "energy": 590},
        ],
        "nutritions": [
            {"name": "protein", "amount": 48},
            {"name": "fat", "amount": 70},
            {"name": "carbs", "amount": 250},
        ],
    },
}

exercises = [
    {"name": "Running", "times": ["morning", "evening"], "duration": "30-45mins"},
    {"name": "Rowing", "times": ["morning"], "duration": "15-20mins"},
    {"name": "Play Tennis", "times": ["evening"], "duration": "1-2hrs"},
    {"name": "Cycling", "times": ["evening"], "duration": "40-50mins"},
]
